//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_Note
    {
        public int id { get; set; }
        public int debit_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_on { get; set; }
        public string edit_by { get; set; }
        public Nullable<System.DateTime> paying_date { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> record_date { get; set; }
        public string customer_name { get; set; }
        public string billing_to { get; set; }
        public string cust_address { get; set; }
        public string customer_phone { get; set; }
        public string bl { get; set; }
        public string container_number { get; set; }
        public string commodity { get; set; }
        public string package_number { get; set; }
        public string vessel { get; set; }
        public string voy { get; set; }
        public Nullable<double> advance_money { get; set; }
        public string debit_fullId { get; set; }
    }
}
