//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public int id { get; set; }
        public Nullable<System.DateTime> bed_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_on { get; set; }
        public string change_by { get; set; }
        public Nullable<System.DateTime> change_on { get; set; }
        public Nullable<System.DateTime> transport_date { get; set; }
        public string truck_sign_number { get; set; }
        public string container_number { get; set; }
        public string container_size { get; set; }
        public string container_net_size { get; set; }
        public string container_amount { get; set; }
        public string import_item_place { get; set; }
        public string export_item_place { get; set; }
        public string extra { get; set; }
        public Nullable<double> road_money { get; set; }
        public Nullable<double> gasolin_money { get; set; }
        public Nullable<double> other_payment { get; set; }
        public Nullable<double> income_per_truck { get; set; }
    }
}
